[package]
name = "mmm-gba"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.14.0"
terminal_size = "0.1.12"
parse_int = "0.4.0"
